@TaskManagement.Backend_HostAddress = https://localhost:7272


GET {{TaskManagement.Backend_HostAddress}}/api/user/1
Authorization Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlODdkMGNlZC02MTMyLTRiYWUtOTBhZi03OTk1MTdhZjIzZmEiLCJuYW1lIjoiYWRtaW5pc3RyYXRvckBsb2NhbGhvc3QiLCJlbWFpbCI6ImFkbWluaXN0cmF0b3JAbG9jYWxob3N0IiwianRpIjoiZjk3NzgzMjgtZWNiNS00MmJjLWE2MTktMTExOTk5ODlkOTAzIiwibmJmIjoxNjg4NDY4MjUxLCJleHAiOjE2ODg0Njk0NTAsImlhdCI6MTY4ODQ2ODI1MX0.KhQbD3D0FBzmYfoE1TzZ2amVPlQBcN-pT67VFw4V8UXtXtFvyfEHRSbRhVW0lPinCADQFghHy4q8bady4LK07Q
